spring:
  application:
    name: Todo
  datasource:
    url: jdbc:mysql://localhost:3306/todo_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Dyc1285604528/
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9090